### ISSUE TITLE
API for the content of all manifest files within the repository for each release or version (tags)

### ISSUE THREAD

**Issue by HassanOnsori** [ecosyste-ms/repos#250]
Hello Andrew! I hope you're having a wonderful day. My name is Hassan, and I'm currently a Ph.D. student collaborating with @tommens and @AlexandreDecan. I was wondering if you would be so kind as to consider providing an API that would allow me to access the content of all manifest files within the repository for each release or version (tags). Allow me to explain the reason behind my request. I'm in the process of extracting a comprehensive list of all GitHub Actions, including their corresponding GitHub repositories and the list of releases for each action. In order to proceed with my data extraction process, the next step involves obtaining the dependencies of actions for each release. Therefore, having access to the content of manifest files such as action.yml, package.json, and package-lock.json, etc for the corresponding release of each action would be incredibly helpful. Your support in this matter would be greatly appreciated. Thank you kindly!

**Comment by andrew** [comment]
Thanks for the feature request, I think this is a great idea. 

There's a little bit of work to do to make this change whilst keeping the performance snappy as the database isn't currently set up to handle repos having more than one set of manifests and there may be some performance implications of changing that, but a short cut may be to have manifests be able to belong to tags.

There's also quite a lot of tags in the database already (137,077,936 approx), so mining the dependencies for each tag is going to take a little while, I can prioritize the known actions repos to speed that up for you.

If you need the data sooner, you can use the https://parser.ecosyste.ms service to generate the same data yourself, passing the `download_url` for each tag for the repo.

**Comment by AlexandreDecan** [comment]
Hello @andrew ,

Thank you for this answer! For Actions, I don't think it is required to gather the manifests for all tags. The "important ones" are the tags corresponding to official releases (i.e., those created using the Release System of GitHub) since they are assumed to correspond to "stable development point" of the corresponding packages; even if it is likely that the two sets of tags (i.e., all tags vs. tags for releases) are quite similar. That said, that already represents quite a huge number of releases/tags to consider (if I remember, @HassanOnsori found more than 50K releases for 2K of the most starred Actions on the Marketplace, and you already have 15 times more Actions in your dataset).

**Comment by andrew** [comment]
I've deployed an initial version of this functionality, example url:

https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/anmol098%2Fwaka-readme-stats/tags/v4/manifests

The api new endpoint is documented in the regular place as well: https://repos.ecosyste.ms/docs/index.html

I'll now get to work on mining all the github action repositories tags, this will be manually enqueued for now, I will set up a cron job once completed to ensure any new tags added to github actions repos get dependencies parsed but I'm not going to start parsing every tag on every repo just yet!

**Comment by AlexandreDecan** [comment]
Awesome, thank you! You're a real magician @andrew ! ;-)

**Comment by AlexandreDecan** [comment]
Btw, is there a way of officially referring to your work and, more generally, to ecosyste.ms in our publications? Some sort of "How do I cite ecosyste.ms?" so that it's easier for you to identify the scientific publications that refer to and are built thanks to your work?

**Comment by AlexandreDecan** [comment]
Potential pointers: 
 - https://libguides.lib.msu.edu/citedata
 - https://www.icpsr.umich.edu/files/ICPSR/enewsletters/iassist.html

Having a DOI could be a good starting point, but I don't know to which extent it's possible to come up with a DOI for a dataset that is constantly evolving :-)

**Comment by andrew** [comment]
Perhaps it would be easier if I publish the data you eventually use as a collection of CSV files to https://zenodo.org/ to make it easier to reproduce the work later and easier to cite?

**Comment by AlexandreDecan** [comment]
That's a really kind suggestion, but we don't want to bother you doing this each time we submit a paper for publication ;-) Our lab is currently composed of 5 researchers (of which 3 PhD students) and two other students will start working in September, likely with data provided by ecosyste.ms :-) A kind of generic "citation" could be interesting to provide (and to use), so that you can easily keep track of all the scientific papers that are using your work, regardless of whether they share the same DOI or not. To be honest, I don't know what's the best strategy and I'm eagerly waiting for @tommens's input on this ;-) 

On a side note, you mention "to reproduce the work later". That's a very good point, esp. given the numerous scientific publications for which there's no way to reproduce the results. On our side, we strive to always provide a replication package containing both the code for the analysis we made for our papers, and a copy of the (processed) data required to execute this code. Often, this data is provided as part of our replication package, and we also provide a README file explaining how this data was obtained (i.e., from libraries.io, ecosyste.ms, etc. and what were the various scripts/notebooks executed on top of this data to generate the "final dataset").

**Comment by andrew** [comment]
I've kicked off the syncing, I've found 230,743 tags across 29,736 repos. There are two new fields on in the tag api `dependencies_parsed_at` and `dependency_job_id`, if `dependency_job_id` is there, then it's in progress, otherwise if `dependencies_parsed_at` is there, then it's complete.

**Comment by andrew** [comment]
Quick update, I've processed dependencies for about 56k tags so far (~25%), it should be all caught up in a couple of days in theory.

**Comment by andrew** [comment]
Parsing progress update: ~50% of all github action repos tags have dependencies parsed

note: completed tags may not be in an obvious order as it's being worked through by primary key rather than grouped by repo or publish datetime.

**Comment by andrew** [comment]
At about 80% now, should be finished by the end of the day today.

**Comment by AlexandreDecan** [comment]
Perfect, thank you!

**Comment by AlexandreDecan** [comment]
Hi @andrew, 

Is there an easy way to detect whether a given tag is associated to a "release" (as created by the release management system provided by GitHub) ? Said differently: is there an easy way to **only** retrieve the releases of a given repository (and not all tags)? 

@HassanOnsori

**Comment by andrew** [comment]
@AlexandreDecan there isn't currently a way to get only releases, I could add that in potentially, what exactly are you looking for in only wanting releases? Is it just the extra content or is there something specific to github actions around releases that I'm not aware of?

**Comment by AlexandreDecan** [comment]
Our goal is to study the dependencies of JavaScript Actions. These dependencies aren't "actual dependencies" in the sense that no package manager installs them when an Action is used in a workflow. Instead, these "dependencies" are vendored with the code of the Action when the single JS file corresponding to the code of the Action is created (usually in "dist/index.js", but that's something that can be changed in action.yml). We aim to retrieve the dependencies that are "bundled" by looking at the "package.json" file in the repository of the Action, assuming that everything listed in this file is actually used to produce the code of the Action. Since every commit can change these dependencies (even if "dist/index.js" is not modified), we will focus on the "official releases" of the Action since these releases correspond to when the "dist/index.js" was generated. That's why we would like to retrieve only (tags corresponding to) "releases" and not all tags. So far, we "manually" relied on the GitHub API to retrieve the list of releases, then we extracted the content of "package.json" file for each of them, then we resolved the dependencies.

**Comment by andrew** [comment]
@AlexandreDecan do you only look at releases that have an `action.yml` in the root of the repository? https://github.com/semantic-release-action/next-release-version for example has many releases but only v1 has an action.yml file, after that it switched to being a workflow instead. GitHub marketplace only considers the single release when listing them: https://github.com/marketplace/actions/next-semantic-release-version

**Comment by AlexandreDecan** [comment]
Yes, we'll filter releases having an `action.yml` at the root of the repository (given a tag, we can already do that using your API).

**Comment by HassanOnsori** [comment]
Hi @andrew,
I have an issue with the endpoint GET /hosts/{hostName}/repositories/{repositoryName}/tags/{tag}/manifests, which I'm using to retrieve manifests for a specific tag.

In some cases, I've noticed that the action.yml file is missing from the API response, even though it's available on GitHub. Here are a few examples:

Repository: ibiqlik/action-yamllint
Tag: v3.0.4
API URL: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/ibiqlik%2Faction-yamllint/tags/v3.0.4/manifests
GitHub URL: https://github.com/ibiqlik/action-yamllint/tree/v3.0.4

Repository: dev-hato/actions-update-gitleaks
Tag: v0.0.17
API URL: https://repos.ecosyste.ms/api/v1/hosts/GitHub/repositories/dev-hato/actions-update-gitleaks/tags/v0.0.17/manifests
GitHub URL: https://github.com/dev-hato/actions-update-gitleaks/tree/v0.0.17

**Comment by andrew** [comment]
@HassanOnsori thanks for reporting, I will investigate tomorrow

**Comment by andrew** [comment]
Turns out that if a manifest doesn't have any dependencies, I've not been saving it, the parser service finds the action.yml (https://parser.ecosyste.ms/api/v1/jobs/ff4e80cc-f64f-4347-98fd-766ccc472d11) file but didn't parse any dependencies out of it.

I'll tweak the code to always create the manifest records even if they have no dependencies.

**Comment by HassanOnsori** [comment]
Great, thanks.

**Comment by andrew** [comment]
@HassanOnsori I've deployed the change, will take a little while to reparse the dependencies for every tag.

I've manually updated those two examples that you shared to check that it's working as expected now.
